export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

type Tables<T> = {
  Row: T;
  Insert: Partial<T>;
  Update: Partial<T>;
  Relationships: [];
};

export type Lead = {
  id: string;
  created_at: string;
  updated_at: string | null;
  customer_name: string;
  phone: string | null;
  email: string | null;
  address: string | null;
  postcode: string | null;
  property_size: string | null;
  service_needed: string | null;
  preferred_date: string | null;
  addons: string[] | null;
  condition_notes: string | null;
  access_notes: string | null;
  parking_notes: string | null;
  lead_source: string | null;
  quote_status: string | null;
  suggested_customer_quote: number | null;
  customer_quote: number | null;
  selected_contractor_id: string | null;
  contractor_cost_estimate: number | null;
  quote_sent_at: string | null;
  follow_up_date: string | null;
  lost_reason: string | null;
  notes: string | null;
  quote_amount?: number | null;
  deposit_required?: boolean | null;
  deposit_amount?: number | null;
  deposit_payment_method?: string | null;
  deposit_payment_link?: string | null;
  deposit_link_sent_date?: string | null;
  deposit_paid?: boolean | null;
  deposit_paid_date?: string | null;
  balance_amount?: number | null;
  balance_payment_link?: string | null;
  balance_link_sent_date?: string | null;
  balance_paid?: boolean | null;
  balance_paid_date?: string | null;
  full_payment_required?: boolean | null;
  full_payment_link?: string | null;
  full_payment_paid?: boolean | null;
  stripe_payment_id?: string | null;
  stripe_checkout_session_id?: string | null;
  payment_notes?: string | null;
  payment_hold?: boolean | null;
  payment_hold_reason?: string | null;
  contractor_payment_eligible?: boolean | null;
  property_condition?: string | null;
  photos_link?: string | null;
  access_parking_key_notes?: string | null;
};

export type Contractor = {
  id: string;
  created_at: string;
  updated_at: string | null;
  name: string;
  phone: string | null;
  email: string | null;
  areas_covered: string | null;
  own_transport: boolean | null;
  years_experience: number | null;
  eot_deep_clean_experience: boolean | null;
  hmrc_status: string | null;
  insurance_certificate_uploaded: boolean | null;
  insurance_file_link: string | null;
  insurance_expiry_date: string | null;
  insurance_cover_amount: number | null;
  id_right_to_work_uploaded: boolean | null;
  id_file_link: string | null;
  contractor_agreement_signed: boolean | null;
  agreement_file_link: string | null;
  rate_card_signed: boolean | null;
  rate_card_file_link: string | null;
  test_job_status: string | null;
  test_job_date: string | null;
  test_job_result: string | null;
  active_rota_approved: boolean | null;
  contractor_status: string | null;
  pause_reason: string | null;
  dbs_status: string | null;
  notes: string | null;
  rate_tier?: string | null;
  fulfilment_priority?: string | null;
  rate_discovery_status?: string | null;
  reliability_score?: number | null;
  quality_score?: number | null;
  rate_notes?: string | null;
  last_contacted_at?: string | null;
  services_offered?: string | null;
  end_of_tenancy_experience?: boolean | null;
  deep_clean_experience?: boolean | null;
  after_builders_experience?: boolean | null;
  oven_window_carpet_experience?: string | null;
  self_employed_status?: string | null;
  public_liability_received?: boolean | null;
  oven_experience?: boolean | null;
  window_experience?: boolean | null;
  carpet_experience?: boolean | null;
  documents_admin_only?: boolean | null;
  bank_details_admin_only?: boolean | null;
};

export type ContractorRate = {
  id: string;
  contractor_id: string;
  rate_card_signed: boolean | null;
  effective_from: string | null;
  studio_rate: number | null;
  one_bed_rate: number | null;
  two_bed_rate: number | null;
  three_bed_rate: number | null;
  four_bed_rate: number | null;
  five_bed_plus_rate: number | null;
  deep_clean_hourly_rate: number | null;
  single_oven_rate: number | null;
  double_oven_rate: number | null;
  range_cooker_rate: number | null;
  carpet_per_room_rate: number | null;
  windows_flat_rate: number | null;
  windows_house_rate: number | null;
  waste_small_load_rate: number | null;
  waste_quarter_van_rate: number | null;
  waste_half_van_rate: number | null;
  waste_full_van_rate: number | null;
  notes: string | null;
};

export type Job = {
  id: string;
  lead_id: string | null;
  created_at: string;
  updated_at: string | null;
  customer_name: string;
  customer_phone: string | null;
  customer_email: string | null;
  job_address: string | null;
  postcode: string | null;
  property_size: string | null;
  service_needed: string | null;
  addons: string[] | null;
  job_date: string | null;
  arrival_window: string | null;
  access_notes: string | null;
  parking_notes: string | null;
  selected_contractor_id: string | null;
  contractor_confirmed: boolean | null;
  contractor_confirmation_time: string | null;
  job_status: string | null;
  completion_form_submitted: boolean | null;
  before_photos_link: string | null;
  after_photos_link: string | null;
  completion_notes: string | null;
  property_secured: boolean | null;
  qa_status: string | null;
  qa_checked_at: string | null;
  qa_notes: string | null;
  customer_issue: boolean | null;
  contractor_issue: boolean | null;
  payment_hold: boolean | null;
  payment_hold_reason: string | null;
  customer_invoice_sent: boolean | null;
  customer_paid: boolean | null;
  payment_cleared: boolean | null;
  customer_payment_date: string | null;
  contractor_paid: boolean | null;
  contractor_payment_date: string | null;
  customer_price: number | null;
  contractor_cost: number | null;
  review_requested: boolean | null;
  review_link_sent_at: string | null;
  invoice_link?: string | null;
  customer_agreement_link?: string | null;
  contractor_job_sheet_link?: string | null;
  job_folder_link?: string | null;
  notes: string | null;
  quote_amount?: number | null;
  deposit_required?: boolean | null;
  deposit_amount?: number | null;
  deposit_payment_method?: string | null;
  deposit_payment_link?: string | null;
  deposit_link_sent_date?: string | null;
  deposit_paid?: boolean | null;
  deposit_paid_date?: string | null;
  balance_amount?: number | null;
  balance_payment_link?: string | null;
  balance_link_sent_date?: string | null;
  balance_paid?: boolean | null;
  balance_paid_date?: string | null;
  full_payment_required?: boolean | null;
  full_payment_link?: string | null;
  full_payment_paid?: boolean | null;
  stripe_payment_id?: string | null;
  stripe_checkout_session_id?: string | null;
  payment_notes?: string | null;
  contractor_payment_eligible?: boolean | null;
  review_request_sent?: boolean | null;
  review_request_sent_date?: string | null;
  review_follow_up_sent?: boolean | null;
  review_follow_up_date?: string | null;
  review_received?: boolean | null;
  review_platform?: string | null;
  review_name?: string | null;
  review_rating?: number | null;
  review_notes?: string | null;
  issue_resolved_before_review_request?: boolean | null;
  checklist_completed?: boolean | null;
  access_key_returned_secured?: boolean | null;
  issues_reported?: boolean | null;
  customer_completion_message_sent?: boolean | null;
  issue_deadline?: string | null;
  job_close_out_status?: string | null;
  payment_method?: string | null;
  payment_type?: string | null;
  expected_gross_profit?: number | null;
  expected_margin_percent?: number | null;
  tide_transfer_reference?: string | null;
  damage_access_issue?: boolean | null;
  damage_access_issue_notes?: string | null;
  contractor_payment_requested?: boolean | null;
  manual_start_approved_by_dom?: boolean | null;
  customer_terms_accepted?: boolean | null;
  cancellation_start_work_consent_accepted?: boolean | null;
};

export type Complaint = {
  id: string;
  job_id: string | null;
  date_opened: string;
  customer_name: string | null;
  contractor_id: string | null;
  complaint_source: string | null;
  issue_type: string | null;
  severity: string | null;
  description: string | null;
  photos_link: string | null;
  complaint_status: string | null;
  re_clean_needed: boolean | null;
  re_clean_date: string | null;
  refund_discount_offered: number | null;
  insurance_claim: boolean | null;
  final_outcome: string | null;
  closed_date: string | null;
  review_risk: boolean | null;
  issue_reported_date?: string | null;
  within_48_hours?: boolean | null;
  covered_by_agreed_checklist?: string | null;
  contractor_responsible?: string | null;
  payment_hold?: boolean | null;
  resolution?: string | null;
};

export type PricingReference = {
  id: string;
  category: string;
  item: string;
  customer_sell_min: number | null;
  customer_sell_max: number | null;
  contractor_cost_min: number | null;
  contractor_cost_max: number | null;
  notes: string | null;
};

export type LaunchChecklistItem = {
  id: string;
  category: string | null;
  task: string;
  details: string | null;
  status: string | null;
  required_before_live: boolean | null;
  blocker: boolean | null;
  owner: string | null;
  due_date: string | null;
  evidence_link: string | null;
  notes: string | null;
  priority?: string | null;
  blocks_launch?: boolean | null;
};

export type AgentOutreach = {
  id: string;
  created_at: string;
  agency: string;
  contact_name: string | null;
  phone: string | null;
  email: string | null;
  area: string | null;
  status: string | null;
  last_contact_date: string | null;
  next_follow_up_date: string | null;
  pitch_sent: boolean | null;
  pricing_sent: boolean | null;
  notes: string | null;
  outcome: string | null;
};


export type JobDocument = {
  id: string;
  created_at: string;
  job_id: string | null;
  contractor_id: string | null;
  lead_id: string | null;
  document_type: string;
  title: string;
  file_link: string | null;
  signed: boolean | null;
  signed_by: string | null;
  signed_at: string | null;
  start_work_consent: boolean | null;
  expiry_date: string | null;
  notes: string | null;
};

export type JobPhoto = {
  id: string;
  created_at: string;
  job_id: string | null;
  contractor_id: string | null;
  photo_stage: string;
  title: string | null;
  file_link: string;
  submitted_by: string | null;
  marketing_permission: boolean | null;
  notes: string | null;
};


export type BusinessSettings = {
  id: string;
  created_at: string;
  updated_at: string | null;
  legal_company_name: string | null;
  company_type?: string | null;
  incorporation_date?: string | null;
  registered_in?: string | null;
  trading_name: string | null;
  company_number: string | null;
  registered_office_address: string | null;
  actual_trading_admin_address: string | null;
  business_email: string | null;
  public_customer_email?: string | null;
  admin_backup_email: string | null;
  phone_number: string | null;
  website?: string | null;
  google_business_profile_status?: string | null;
  ico_registration_status?: string | null;
  solicitor_review_status?: string | null;
  google_review_link?: string | null;
  google_review_link_saved?: boolean | null;
  service_area_business?: boolean | null;
  storefront_required?: boolean | null;
  tide_account_status: string | null;
  stripe_account_status: string | null;
  stripe_payout_bank?: string | null;
  insurance_status: string | null;
  ico_application_reference?: string | null;
  public_liability_provider?: string | null;
  public_liability_policy_number?: string | null;
  public_liability_cover_amount?: number | null;
  public_liability_start_date?: string | null;
  public_liability_end_date?: string | null;
  professional_indemnity_status?: string | null;
  professional_indemnity_provider?: string | null;
  professional_indemnity_cover_amount?: number | null;
  professional_indemnity_certificate_upload?: string | null;
  professional_indemnity_expiry_date?: string | null;
  companies_house_auth_code_stored_securely: boolean | null;
  hmrc_utr_received: boolean | null;
  corporation_tax_setup_status: string | null;
  vat_registered?: boolean | null;
  actual_trading_admin_address_restricted?: boolean | null;
  auth_code_restricted?: boolean | null;
  service_area_notes?: string | null;
  notes: string | null;
};

export type FinanceItem = {
  id: string;
  created_at: string;
  job_id: string | null;
  lead_id: string | null;
  item_type: string;
  category: string;
  description: string | null;
  amount: number;
  due_date: string | null;
  paid_date: string | null;
  payment_status: string | null;
  payment_method: string | null;
  reference: string | null;
  evidence_link: string | null;
  notes: string | null;
};

export type AuditLogItem = {
  id: string;
  created_at: string;
  entity_type: string;
  entity_id: string | null;
  action: string;
  summary: string | null;
  metadata: Json | null;
  actor: string | null;
};



export type InsuranceChecklist = {
  id: string;
  created_at: string;
  updated_at: string | null;
  broker_insurer_contacted: string | null;
  public_liability_quoted: boolean | null;
  professional_indemnity_quoted: boolean | null;
  employers_liability_needed: string | null;
  bona_fide_subcontractors_allowed: string | null;
  subcontractors_must_hold_own_pl: boolean | null;
  minimum_subcontractor_pl_cover: string | null;
  pdd_site_visits_access_qa_key_photos_touchups_covered: string | null;
  arranging_managing_vetting_admin_risk_covered: string | null;
  policy_responds_if_customer_claims_against_pdd: string | null;
  exclusion_external_windows: boolean | null;
  exclusion_carpet_cleaning: boolean | null;
  exclusion_waste: boolean | null;
  exclusion_jet_washing: boolean | null;
  exclusion_after_builders: boolean | null;
  exclusion_oven_cleaning: boolean | null;
  policy_purchased: boolean | null;
  policy_start_date: string | null;
  renewal_date: string | null;
  policy_documents_uploaded: boolean | null;
  evidence_link: string | null;
  launch_blocker: boolean | null;
  status: string | null;
  notes: string | null;
  model_confirmed_by_broker: boolean | null;
  public_liability_provider?: string | null;
  public_liability_policy_number?: string | null;
  public_liability_cover_amount?: number | null;
  occupation_class?: string | null;
  cover_start_date?: string | null;
  cover_end_date?: string | null;
  professional_indemnity_status?: string | null;
  professional_indemnity_provider?: string | null;
  professional_indemnity_cover_amount?: number | null;
  professional_indemnity_certificate_upload?: string | null;
  professional_indemnity_expiry_date?: string | null;
  policy_wording_link?: string | null;
  admin_only_documents?: boolean | null;
};

export type LegalDocumentChecklist = {
  id: string;
  created_at: string;
  updated_at: string | null;
  document_name: string;
  current_version: string | null;
  status: string | null;
  solicitor_review_needed: boolean | null;
  last_updated: string | null;
  notes: string | null;
  file_link: string | null;
  launch_blocker: boolean | null;
};

export type TestClean = {
  id: string;
  created_at: string;
  updated_at: string | null;
  contractor_id: string | null;
  contractor_name: string | null;
  test_clean_address: string | null;
  test_clean_type: string | null;
  scheduled_at: string | null;
  agreed_test_fee: number | null;
  checklist_sent: boolean | null;
  before_photos_received: boolean | null;
  after_photos_received: boolean | null;
  completion_form_received: boolean | null;
  quality_score: number | null;
  communication_score: number | null;
  punctuality_score: number | null;
  passed: boolean | null;
  active_approval_decision: string | null;
  notes: string | null;
  evidence_link: string | null;
};


export type MessageTemplate = {
  id: string;
  created_at: string;
  updated_at: string | null;
  template_id: string;
  template_name: string;
  category: string;
  stage_status: string | null;
  channel: string | null;
  subject_line: string | null;
  message_body: string;
  variables_used: string | null;
  active: boolean | null;
  notes: string | null;
};

export type CrmFormBlueprint = {
  id: string;
  created_at: string;
  updated_at: string | null;
  form_key: string;
  form_name: string;
  form_type: string | null;
  linked_table: string | null;
  purpose: string | null;
  required_fields: string | null;
  optional_fields: string | null;
  status: string | null;
  owner: string | null;
  notes: string | null;
  active: boolean | null;
};

export type Database = {
  public: {
    Tables: {
      leads: Tables<Lead>;
      contractors: Tables<Contractor>;
      jobs: Tables<Job>;
      complaints: Tables<Complaint>;
      pricing_reference: Tables<PricingReference>;
      launch_checklist: Tables<LaunchChecklistItem>;
      agent_outreach: Tables<AgentOutreach>;
      contractor_rates: Tables<ContractorRate>;
      job_completion_submissions: Tables<Record<string, unknown>>;
      operator_profiles: Tables<Record<string, unknown>>;
      job_documents: Tables<JobDocument>;
      job_photos: Tables<JobPhoto>;
      finance_items: Tables<FinanceItem>;
      audit_log: Tables<AuditLogItem>;
      business_settings: Tables<BusinessSettings>;
      insurance_checklist: Tables<InsuranceChecklist>;
      legal_documents_checklist: Tables<LegalDocumentChecklist>;
      test_cleans: Tables<TestClean>;
      message_templates: Tables<MessageTemplate>;
      crm_form_blueprints: Tables<CrmFormBlueprint>;
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
